/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tyxl.uielements;

import org.tyxl.controller.MainWindow;

/**
 *
 * @author Daniel
 */
public class MachineMacrosDialog extends javax.swing.JDialog {
MainWindow mw;
    /**
     * Creates new form MachineMacrosDialog
     */
    public MachineMacrosDialog(java.awt.Frame parent, boolean modal, MainWindow mw) {
        super(parent, modal);
        this.mw=mw;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        macroInstructions = new javax.swing.JLabel();
        customGcodeButton1 = new javax.swing.JButton();
        customGcodeButton2 = new javax.swing.JButton();
        customGcodeButton3 = new javax.swing.JButton();
        customGcodeButton4 = new javax.swing.JButton();
        customGcodeButton5 = new javax.swing.JButton();
        customGcodeText5 = new javax.swing.JTextField();
        customGcodeText4 = new javax.swing.JTextField();
        customGcodeText3 = new javax.swing.JTextField();
        customGcodeText2 = new javax.swing.JTextField();
        customGcodeText1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        macroInstructions.setText("Macros, you can add multiple lines of gcode by seperating with ;");

        customGcodeButton1.setText("C1");
        customGcodeButton1.setEnabled(false);
        customGcodeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeButton1ActionPerformed(evt);
            }
        });

        customGcodeButton2.setText("C2");
        customGcodeButton2.setEnabled(false);
        customGcodeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeButton2ActionPerformed(evt);
            }
        });

        customGcodeButton3.setText("C3");
        customGcodeButton3.setEnabled(false);
        customGcodeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeButton3ActionPerformed(evt);
            }
        });

        customGcodeButton4.setText("C4");
        customGcodeButton4.setEnabled(false);
        customGcodeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeButton4ActionPerformed(evt);
            }
        });

        customGcodeButton5.setText("C5");
        customGcodeButton5.setEnabled(false);
        customGcodeButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeButton5ActionPerformed(evt);
            }
        });

        customGcodeText5.setToolTipText("");
        customGcodeText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeText5ActionPerformed(evt);
            }
        });

        customGcodeText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeText4ActionPerformed(evt);
            }
        });

        customGcodeText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeText3ActionPerformed(evt);
            }
        });

        customGcodeText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeText2ActionPerformed(evt);
            }
        });

        customGcodeText1.setText("G91 X0 Y0;");
        customGcodeText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customGcodeText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customGcodeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customGcodeText1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customGcodeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customGcodeText2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customGcodeButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customGcodeText4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customGcodeButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customGcodeText3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customGcodeButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customGcodeText5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(macroInstructions)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(macroInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customGcodeButton1)
                    .addComponent(customGcodeText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customGcodeButton2)
                    .addComponent(customGcodeText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customGcodeButton3)
                    .addComponent(customGcodeText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customGcodeButton4)
                    .addComponent(customGcodeText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customGcodeButton5)
                    .addComponent(customGcodeText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customGcodeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeButton1ActionPerformed
        mw.executeCustomGcode(this.customGcodeText1.getText());
    }//GEN-LAST:event_customGcodeButton1ActionPerformed

    private void customGcodeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeButton2ActionPerformed
        mw.executeCustomGcode(this.customGcodeText2.getText());
    }//GEN-LAST:event_customGcodeButton2ActionPerformed

    private void customGcodeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeButton3ActionPerformed
        mw.executeCustomGcode(this.customGcodeText3.getText());
    }//GEN-LAST:event_customGcodeButton3ActionPerformed

    private void customGcodeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeButton4ActionPerformed
        mw.executeCustomGcode(this.customGcodeText4.getText());
    }//GEN-LAST:event_customGcodeButton4ActionPerformed

    private void customGcodeButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeButton5ActionPerformed
        mw.executeCustomGcode(this.customGcodeText5.getText());
    }//GEN-LAST:event_customGcodeButton5ActionPerformed

    private void customGcodeText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeText5ActionPerformed
        mw.settings.setCustomGcode5(this.customGcodeText5.getText());
    }//GEN-LAST:event_customGcodeText5ActionPerformed

    private void customGcodeText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeText4ActionPerformed
        mw.settings.setCustomGcode4(this.customGcodeText4.getText());
    }//GEN-LAST:event_customGcodeText4ActionPerformed

    private void customGcodeText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeText3ActionPerformed
        mw.settings.setCustomGcode3(this.customGcodeText3.getText());
    }//GEN-LAST:event_customGcodeText3ActionPerformed

    private void customGcodeText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeText2ActionPerformed
        mw.settings.setCustomGcode2(this.customGcodeText2.getText());
    }//GEN-LAST:event_customGcodeText2ActionPerformed

    private void customGcodeText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customGcodeText1ActionPerformed
        mw.settings.setCustomGcode1(this.customGcodeText1.getText());
    }//GEN-LAST:event_customGcodeText1ActionPerformed

   public void updateCustomGcodeControls(boolean enabled) {
        this.customGcodeButton1.setEnabled(enabled);    
        this.customGcodeButton2.setEnabled(enabled);   
        this.customGcodeButton3.setEnabled(enabled);
        this.customGcodeButton4.setEnabled(enabled);
        this.customGcodeButton5.setEnabled(enabled);        
        this.customGcodeText1.setEnabled(enabled);
        this.customGcodeText2.setEnabled(enabled);
        this.customGcodeText3.setEnabled(enabled);
        this.customGcodeText4.setEnabled(enabled);
        this.customGcodeText5.setEnabled(enabled);
    }
   public static void setCustom1(String custom1){
       customGcodeText1.setText(custom1);
   }
    public static void setCustom2(String custom2){
       customGcodeText1.setText(custom2);
   }
     public static void setCustom3(String custom3){
       customGcodeText1.setText(custom3);
   }
      public static void setCustom4(String custom4){
       customGcodeText1.setText(custom4);
   }
       public static void setCustom5(String custom5){
       customGcodeText1.setText(custom5);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customGcodeButton1;
    private javax.swing.JButton customGcodeButton2;
    private javax.swing.JButton customGcodeButton3;
    private javax.swing.JButton customGcodeButton4;
    private javax.swing.JButton customGcodeButton5;
    private static javax.swing.JTextField customGcodeText1;
    private static javax.swing.JTextField customGcodeText2;
    private static javax.swing.JTextField customGcodeText3;
    private static javax.swing.JTextField customGcodeText4;
    private static javax.swing.JTextField customGcodeText5;
    private javax.swing.JLabel macroInstructions;
    // End of variables declaration//GEN-END:variables
}
